### ISSUE TITLE
Архив для заданий.

### ISSUE THREAD

**Issue by Citramonkin** [TechnoFractal/TelegrammBot#14]
Нужно реализовать архив в админке, в который будут попадать удаленные из бота задания. Чтобы они не исчезали в "небытие", а складировались там. Иногда нужно просматривать историю заданий, анализировать их эффективность, копировать текст.

**Comment by olgapshen** [comment]
Сделала )
Задеплоила на тестовый контур: @olgakoshka_bot
Проверь функцилнал и я перенесу на прод.
Комментарий: "удалить из удаленных" - это "восстановить"
