### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by egoegoego** [TechnoFractal/TelegrammBot#2]
-возможность редактировать и добавлять новые пункты в меню(информация, связь, ссылки и т.д.), т.к. со временем их кол-во скорее всего будет увеличиваться.

-выдача заданий:
1)путь к задачам (сначала в меню человек открывает вкладку задания, потом уже идет выбор заданий по сложности)
2)после нажатия на кнопку выдачи заданий (легкие,средние,тяжелые) открывается меню с кнопками на сами задания (задание1,2....(название1,2...)) уже после нажатия на кнопки бот выдает текст с заданием.

**Comment by olgapshen** [comment]
Распишите логику с выводом заданий подробнее, что делать если заданий будет 1000?
Редакцию пунктов меню, пока отложим, пока программно.

**Comment by Citramonkin** [comment]
Не вижу смысла городить огород как в прошлом боте, ведь этот поддерживает выдачу заданий по очереди. 
жмякнул кнопку простое задание- получил задание. Жмякнул еще раз, получил следующее. 
Единственное, что под каждым заданием должны быть две кнопки
1) Отложить - переходит к следующему заданию, само задание попадает в конец очереди на выдачу.
2) Сделал - задание пропадает из очереди для этого пользователя.
Это же реализуемо? Что то подобное было уже вроде сделано ранее.

**Comment by olgapshen** [comment]
Да ) реализуемо )

**Comment by Citramonkin** [comment]
что под каждым заданием должны быть две кнопки

Отложить - переходит к следующему заданию, само задание попадает в конец очереди на выдачу.
Сделал - задание пропадает из очереди для этого пользователя.

**Comment by olgapshen** [comment]
Добавила кнопки на тестовом конуре.
При нажатии на сервер передается вся необходимая информация.
Сервер реагирует, посылая имя действия и номер поста, но пока не вносит изминения в базу.

**Comment by olgapshen** [comment]
Допилила, задеплоила на прод.
