### ISSUE TITLE
Добавить уведомления!

### ISSUE THREAD

**Issue by Citramonkin** [TechnoFractal/TelegrammBot#4]
Добавить уведомление о новых заданиях всем пользователям!

**Comment by olgapshen** [comment]
Сделаем

**Comment by Citramonkin** [comment]
Тоже АП!

**Comment by olgapshen** [comment]
Добавила уведомления!!!
Но, маленькое "но" - уведомления поступят после того, как пользователь получит сообщение "Молодцы, вы выполнили все задания".
Если новое задание было написано, но пользователь не получал сообщения - "молодцы", он уведомление на получит, но это и хорошо, меньше спама.

**Comment by Citramonkin** [comment]
Уведомление массовое, всем подписчикам. Есть новое задание - есть уведомление. Отписку не делаем. Пусть пользуются встроенной заглушкой самого телеграма.

**Comment by olgapshen** [comment]
Сделала.
Но еще одно "но".
В первой версии бота я не сохраняла chat_id.
Оповещение будут получать те кто со вчерашнего коммита выбрали или выберут хоть одно задание, что бы прописался id сессии.
