### ISSUE TITLE
В раздел Инфо добавить эту информацию.

### ISSUE THREAD

**Issue by Citramonkin** [TechnoFractal/TelegrammBot#5]
D. Teller, [26.01.18 14:17]
Если ты не сдался, и не собираешься просто сидеть на диване - присоединяйся к нашим чатам в телеграм, предназначенным для борьбы против кремлёвской пропаганды.

Именно ты нам и нужен. Россия будет свободной!

▪️"Уютная Оппозиция" - основной чат.
https://t.me/opposition1

▪️"Уютные Новости" - новостной канал.
https://t.me/UORFNEWS

▪️"Восточный Берлин" - чат обсуждения новостей политики, и истории.
https://t.me/Ost_Berlin

▪️"Беседка 404" - посторонние обсуждения.
https://t.me/BESEDKA404

▪️"Opposition in DarkNet" - нестандартные воздействия на пропагандистские сайты режима.
https://t.me/DARK_NET_1

▪️"Уютный Антибот" - контрпропаганда, на провластных площадках в сети.
https://t.me/joinchat/CzEBnBK7-SgGUZSif6Yl2w

Наши соратники:
▪️"Сопротивление"
О движении — http://telegra.ph/Dvizhenie-Soprotivlenie-11-01

https://t.me/shakethesystem

▪️"Антитролль" - этот бот сделан для тех, кто хочет помочь освобождению России, но боится или не может выйти на улицу и для тех, кто не хочет сидеть без дела в перерывах между митингами.
@kremIin_bot

▪️"Альянс Протестных Сил"
Мы - Альянс Протестных Сил. Наша цель - объединить разрозненные протестные организации.
https://t.me/manezhkachat

Региональные чаты:
▪️"Импичмент - Москва"
https://t.me/joinchat/D2tD3z_iTcmSB7510DI-3g

▪️"N: Протестный Краснодар"
https://t.me/pro_krasnodar

▪️"Протестная Сибирь"
https://t.me/protestSiberia

**Comment by olgapshen** [comment]
Done
