### ISSUE TITLE
Описание бота добавить.

### ISSUE THREAD

**Issue by Citramonkin** [TechnoFractal/TelegrammBot#6]
Привет!
 Я антибот, и я создан чтобы помочь тебе бороться с "кремлеботами". Ниже есть кнопки, нажимая на которые ты будешь получать задания. Они разделены по степени сложности на 3 группы.
Так же есть кнопка с полезной информацией и кнопка для обратной связи с контактами, куда ты можешь присылать свои предложения, пожелания и даже свои собственные задания! 
Вместе мы сможем поменять мир к лучшему, и начнем прямо сейчас!

**Comment by olgapshen** [comment]
Done
