### ISSUE TITLE
Править Описание, Инфо и Контакты бота из админки

### ISSUE THREAD

**Issue by Citramonkin** [TechnoFractal/TelegrammBot#7]
Реально ли расширить функционал админки, чтоб это все легко и быстро можно было править?

**Comment by olgapshen** [comment]
Да, реально ) сейчас сделаю

**Comment by olgapshen** [comment]
На выходных )

**Comment by Citramonkin** [comment]
В общем, В разделе ИНФО и Контакты нужна возможность добавлять подразделы из админки. В виде кнопки, которой можно давать название. По нажатию на неё пользователь должен увидеть контент. На этом все, запуск! )
