### ISSUE TITLE
Реализовать набор заданий для привлечения разработчиков

### ISSUE THREAD

**Issue by Lady3mlnm** [TechnoFractal/TelegrammBot#9]
Додумать и реализовать на боте последовательность заданий, которые помогут начинающим разработчикам набрать минимальный набор скилов для вливания в нашу техническую команду. Список составляется из предположения, что человек на старте уже имеет некоторый опыт программирования, но сидит на Windows. Под задания по возможности подобрать учебный материал.

Предварительный список заданий:

- Установить Линукс.

- Ознакомиться с базовыми настройками Линукса и его файловой структурой. Настроить системы для повседневного использования. Ознакомиться с базовыми программами. Научиться инсталлировать новые.

- Обучиться базовым командам работы с терминалом (навигация по дереву, создание/удаление файлов и директорий, копирование/перемещение/переименование, получение базовой информации о системе, sudo)

- Более серьёзные команды работы с терминалом (опции команд -h/--help, основы работы с man, вывод содержимого файла в консоль, изменение прав доступа на файл, получение более глубоких сведений о системе и железе, работа с архивами, монтирование и отмонтирование дисков, создание загрузочной флешки).

- Установить vim и обучиться основам работы в нём. Рекомендуем vimtutor (после установки редактора введите в консоль это слово).

- Основы создания скриптов и работы с Bash /\*Стоит указать пару хороших курсов\*/

- Научиться встраивать портативные программы в систему и генерировать программы из исходников /\*Стоит провести несколько примеров программ, которые человек должен полноценно установить в систему\*/

- Разобраться, какие на Linux есть среды разработки под предпочитаемые вами языки программирования (или языки, которые вы планируете изучить в ближайшее время). Установить хотя бы одну из них.

- Создать аккаунт на гитхабе. Понять его основные принципы работы и базовую терминологию. Сделать форк любого репозитория (можете использовать репозитории ТехноФрактала). Научиться делать в него коммиты. Вступить в нашу группу разработчиков на гитхабе.

- Понять основы работы с md-файлами.

- Создать локальный сервер через ручную установку компонентов (следуя инструкции в бот-репозирории, установить и сконфигурировать Apache2, Nginx, PHP, Composer, CodeIgniter, NodeJS)

- Развернуть на локальном сервере наш бот.

- Разобраться с SSH-ключами: как их генерировать и как подключаться с их помощью к серверу.

- Понять основы работы с MySQL /\*Стоить привести пару хороших курсов. Я поняла, что курсом с w3schools.com именно для нашего случая лучше не пользоваться из-за его направленности в несколько ином направлении\*/

/\*Ещё нужны некоторые задания, чтобы человек понимал основы сетевых технологий и технологий безопасности.\*/

**Comment by olgapshen** [comment]
Супер!

**Comment by olgapshen** [comment]
Так и Теллера и остальных подключай

**Comment by Lady3mlnm** [comment]
На Теллере и так много. Сам подключится, если сочтёт нужным.

**Comment by Lady3mlnm** [comment]
Я разместила копию списка на сайте, немного уточнив некоторые пункты и указав некоторые источники информации:
http://technofractal.tk/for-beginning-developers

**Comment by olgapshen** [comment]
Супер!
